### ISSUE TITLE
Results missing in engine.queryBindings 

### ISSUE THREAD

**Issue by andrefs** [belayeng/quadstore-comunica#6]
I've run into a problem using `engine.queryBindings`: I don't seem to get as many results back as I should.

I've created a repository with an MWE:
https://github.com/andrefs/quastore-mwe

Basically it loads an N-Triples file with 100 triples to a LevelDB db using quadstore. Then it queries them with `SELECT * WHERE { ?s ?p ?o }`. I only get 1 result back.

This example was boiled down from my initial use case where I was using the full WordNet file and a more complex query.

I'm not sure if this is an actual problem or if I'm doing something wrong (apologies in advance if that's the case). 

If there is indeed a bug, I don't know if it is caused by `quadstore`, `quadstore-comunica` or even `classic-level`.

Please let me know if there's any more information that I can provide.

**Comment by jacoscaz** [comment]
Hi @andrefs ! The problem in your code is that you are closing the store before the end of the stream as the `await store.close();` sits outside of the callback handler for the `end` event. Simply move `store.close()` into the handler and you'll get all quads out.

**Comment by andrefs** [comment]
:facepalm: Thanks! and sorry for opening the issue :sweat:

**Comment by jacoscaz** [comment]
No worries :)
